import numpy as np
import matplotlib.pyplot as plt

plt.figure(1)
a, b, c, d = np.loadtxt("input/Lab 4 - sheet5.csv", delimiter=',', unpack= True, skiprows= 1)
plt.plot(a, b, label='R = 1850')
plt.plot(a, c, label='R = 3700')
plt.plot(a, d, label='R = 7400')
axes = plt.gca()
axes.set_xlim(15000, 45000)
axes.set_ylim(-40, 0)
plt.legend()
plt.savefig("output/different rs.png")

plt.figure(2)
plt.title('Series')
ax, ay = np.loadtxt("input/Lab 4 - Voltage cap.csv", delimiter=',', unpack= True, skiprows= 1)
bx, by = np.loadtxt("input/Lab 4 - phase cap.csv", delimiter=',', unpack= True, skiprows= 1)
cx, cy = np.loadtxt("input/Lab 4 - Voltage Cap Para.csv", delimiter=',', unpack= True, skiprows= 1)
dx, dy = np.loadtxt("input/Lab 4 - phase Cap Para.csv", delimiter=',', unpack= True, skiprows= 1)
plt.plot(ax, ay, label='Voltage')
plt.plot(bx, by, label='Phase')
plt.legend()
axes = plt.gca()
axes.set_xlim(0, 20000)
plt.savefig("output/series.png")

plt.figure(3)
plt.title('Parallel')
plt.plot(cx, cy, label='Voltage')
plt.plot(dx, dy, label='Phase')
plt.legend()
axes = plt.gca()
axes.set_xlim(0, 45000)
plt.savefig("output/parallel.png")


x0, y0 = np.loadtxt("input/tek0026CH1.csv", delimiter=',', unpack= True, skiprows= 21)
x1, y1 = np.loadtxt("input/tek0027CH1.csv", delimiter=',', unpack= True, skiprows= 21)
x2, y2 = np.loadtxt("input/tek0028CH1.csv", delimiter=',', unpack= True, skiprows= 21)
x3, y3 = np.loadtxt("input/tek0029CH1.csv", delimiter=',', unpack= True, skiprows= 21)
x4, y4 = np.loadtxt("input/tek0030CH1.csv", delimiter=',', unpack= True, skiprows= 21)
x5, y5 = np.loadtxt("input/tek0031CH1.csv", delimiter=',', unpack= True, skiprows= 21)
x6, y6 = np.loadtxt("input/tek0032CH1.csv", delimiter=',', unpack= True, skiprows= 21)
x7, y7 = np.loadtxt("input/tek0033CH1.csv", delimiter=',', unpack= True, skiprows= 21)
x8, y8 = np.loadtxt("input/tek0034CH1.csv", delimiter=',', unpack= True, skiprows= 21)
x9, y9 = np.loadtxt("input/tek0035CH2.csv", delimiter=',', unpack= True, skiprows= 21)
x10, y10 = np.loadtxt("input/tek0036CH2.csv", delimiter=',', unpack= True, skiprows= 21)


plt.figure(4)
plt.plot(x0, y0)
plt.plot(x1, y1)
plt.plot(x2, y2)
axes = plt.gca()
axes.set_xlim(-.00025, .00025)

f, axarr = plt.subplots(8, sharex=True)
axarr[0].plot(x3, y3)
axarr[1].plot(x4, y4)
axarr[2].plot(x5, y5)
axarr[3].plot(x6, y6)
axarr[4].plot(x7, y7)
axarr[5].plot(x8, y8)
axarr[6].plot(x9, y9)
axarr[7].plot(x10, y10)

plt.show()